name: rbbst

on:
  push:
    branches:
    - main

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.2'
    - name: run tests
      working-directory: ./rbbst
      run: go test -v -bench=.