name: rbbst

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.2'
      - name: run tests
        working-directory: ./rbbst
        run: go test -v -bench=.

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.2'
      - name: go mod tidy
        working-directory: ./rbbst
        run: go mod tidy
      - name: go list
        working-directory: ./rbbst
        run: GOPROXY=proxy.golang.org go list -m github.com/${{ github.respository }}/rbbst@${{ github.ref_name }}