name: rbbst

on: [push]

jobs:
  test_rbbst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.2'
      - name: run test rbbst
        working-directory: ./rbbst
        run: go test -v -bench=.
      
  test_orderbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.2'
      - name: run test orderbook
        working-directory: ./orderbook
        run: go test -v -bench=.

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: [test_rbbst, test_orderbook]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.2'
      - name: go mod tidy
        run: go mod tidy
      - name: go list
        run: GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${{ github.ref_name }}